### ISSUE TITLE
Reboot issue.

### ISSUE THREAD

**Issue by MegaShinySnivy** [MechanicalDragon0687/BAXTools#1]
Using BAX causes Luma's reboot functionality to break. The system hangs, before shutting down. No errdisp displays.
Luma: 10.0.1
Bootloader: B9S.
System model: New 3ds XL, USA version.
System version: 11.10. 
Splash: On and used.
Other boot programs: None.

**Comment by MechanicalDragon0687** [comment]
This is a tutorial wiki and script for building bax videos, I will do some testing but this would be best to take up with the BAX developer or luma developer.
Also, Luma 10 breaks some errdisp functions, testing on 9.1 would be preferable

**Comment by MegaShinySnivy** [comment]
Tested with Luma 9.1. No hang or errdisp appears. It seems to be an error with Luma 10.0.1. Sorry, thought this was for BAX specifically.

**Comment by MechanicalDragon0687** [comment]
Good to hear.
