### ISSUE TITLE
Bats are not working

### ISSUE THREAD

**Issue by BlueDawnx** [MechanicalDragon0687/BaxTools#1]
Hey, thank you for your tool. I tried to do a bootscreen for both screens but im failing to do so. I draged my 720 x240 mp4 at the bat buts its not doing anything. It starts converting when im draging it to the exe file but then its only on one screen. Could u help me out.

**Comment by MechanicalDragon0687** [comment]
could you upload the video file you are converting to someplace so that i can reproduce with your file?

**Comment by BlueDawnx** [comment]
Sure here
https://drive.google.com/drive/folders/1cO_mL_EHpkEQ91qT1-dsBDNucXZ75-46?usp=sharing

**Comment by MechanicalDragon0687** [comment]
which file specifically is failing?
it doesnt handle spaces in filenames, btw

**Comment by BlueDawnx** [comment]
lumanintendo sideways 240x720.mp4 and luma3ds 720x240.mp4 . u were right, the spaces in my filepath were my problem. I just was able to convert them now but still im not able to display these files on both screens. The Boot animation is only shown on the top screen. what did i wrong? heres a pic https://ibb.co/McKFw4w

**Comment by MechanicalDragon0687** [comment]
your lumanintendo sideways seems incompatible to me, i will have to test the other later when i have access to my system.

nvm, i used someone else's. Converted your luma3ds 720x240.mp4 just fine

you may not have waited long enough for conversion
 ![image](https://user-images.githubusercontent.com/43786828/80770767-08af6b00-8b06-11ea-918c-240ce7db7862.png)

![20200430_170948_1](https://user-images.githubusercontent.com/43786828/80770708-d00f9180-8b05-11ea-980d-3d1ac2eea49b.gif)

**Comment by MechanicalDragon0687** [comment]
just in case you cant figure it out, heres the file i got by running the file using the sideways bat.

https://drive.google.com/file/d/1AIXmAX0AJecBxb8atbgnXSBgoYRZr5Ws/view?usp=sharing

**Comment by BlueDawnx** [comment]
strange, now its working just fine on my side too. sorry, for the taking your time and thx :) One more thing: After Conversation the clip is getting resized and everything got a bit small, what can i do to avoid this?

**Comment by MechanicalDragon0687** [comment]
because its a single video, it has to fit on both screens. Because of this, you are limited to 320x240 on each screen (320 is the width of the smaller screen) 
your video was 240x720, which had to be turned into a portrait video. 
720/2 is 360, which was too large to fit so it was resized.  

try 320x480
