### ISSUE TITLE
Bax Converter does not convert.

### ISSUE THREAD

**Issue by Vinnievovi** [MechanicalDragon0687/BaxTools#2]
Every time I start a conversion "Failed to open video" appears. The video is mp4, I called it Video, I also tried different sizes, 400x320 and 320x480, but nothing ... For the rest everything works, I tried with some bax already created and everything works very well.

**Comment by MechanicalDragon0687** [comment]
can you upload the video to this issue or link it so i can test it locally?
do you see any errors other than "failed to open video"?
are you making sure there are no spaces in the filepath?

keep in mind mp4 is just a container so depending on the video codec used, the file may not be compatible.

**Comment by Vinnievovi** [comment]
I uploaded a demonstration video.
https://www.mediafire.com/download/bf8zr8fz29tih6a
Here instead there is the original file.
https://www.mediafire.com/download/s39jhkw9kj6vfpw

**Comment by MechanicalDragon0687** [comment]
something may be blocking the ability to open the file using the app. I just tested and it worked fine on my end. 
It might have something to do with antivirus, file location (desktop may be blocked for access maybe) or something else. This does not appear to be an app issue (as the app is telling you that something is blocking access to the file)

My test:
make C:\Test (not generally recommended but good to eliminate folder location issues)
ensure my user has access to files in C:\Test 
download video.mp4 to C:\test
put baxtools files in C:\test
drag video.mp4 over CONVERT_TO_TOPSCREEN.bat
copy Video.bax to the SD:/Bax/ folder
boot 3ds

I have seen access issues occur when using OneDrive to sync desktop/documents/downloads folders, for example.
Try another location.

**Comment by Vinnievovi** [comment]
Nothing to do, it still doesn't work, maybe it's a problem with my PC.  I also uninstalled the antivirus, but nothing.  If it's possible for you, if it doesn't bother you, could you create a bax of that video and upload it?  At least so I can use it on my 3ds.

**Comment by MechanicalDragon0687** [comment]
https://www.mediafire.com/file/dlfkcls27z2ijeo/videos.7z/file

**Comment by R132736434** [comment]
> https://www.mediafire.com/file/dlfkcls27z2ijeo/videos.7z/file

hi can you pls help me i have the same issue here 
this is the file https://www.mediafire.com/file/cimdiguuk288y3m/nintendoswitchstartup.mp4/file
