### ISSUE TITLE
bax converter does not work

### ISSUE THREAD

**Issue by R132736434** [MechanicalDragon0687/BaxTools#5]
idk why but bac converter whenever i want to turn any mp4 file it said failed to open video i tried several other videos with all qualities but nothing seems to work if anyone has a solution pls help me
this is the video i wanna convert 
https://www.mediafire.com/file/cimdiguuk288y3m/nintendoswitchstartup.mp4/file

**Comment by MechanicalDragon0687** [comment]
For this you will need a direct, public download link to your video. I am not going to troubleshoot random file share sites. figure out how to link your video for downloading

https://github.com/MechanicalDragon0687/BaxConverterGA  

Click "Use This Template" then "Create new repository"
Use any name you want
Once Created, go to Actions at the top
Click "Convert Video" on the left to select the Convert Video workflow
Click the "Run workflow" dropdown on the right and fill out the entries
Click the green "Run workflow" option
wait for it to complete
download the video file from the assets/uploads at the bottom of that run once it completes.

**Comment by R132736434** [comment]
> For this you will need a direct, public download link to your video. I am not going to troubleshoot random file share sites. figure out how to link your video for downloading
> 
> https://github.com/MechanicalDragon0687/BaxConverterGA
> 
> Click "Use This Template" then "Create new repository" Use any name you want Once Created, go to Actions at the top Click "Convert Video" on the left to select the Convert Video workflow Click the "Run workflow" dropdown on the right and fill out the entries Click the green "Run workflow" option wait for it to complete download the video file from the assets/uploads at the bottom of that run once it completes.

i'm sorry it said an error had occurred idk why but i think it's because mediafire's linkif you have a solution for this pls

**Comment by R132736434** [comment]
i fix the link by replacing mediafire by drive and it worked but a new error join the battle it is this one 
Error: No files were found with the provided path: videofile.bax. No artifacts will be uploaded.
idk if you can help me with it

**Comment by Linguardium** [comment]
you did not provide a direct download link so the "video" it downloaded was just the google drive downloads page. 

use the direct "download" link not a view link

**Comment by MechanicalDragon0687** [comment]
lol, you are a nicer person than i. I wasnt going to help but since Ling got you part of the way there...

you can use a site like https://sites.google.com/site/gdocs2direct/ to convert your google drive links to direct download links that should work. if you still cant get it, add it as a file to your repository in github, then click the file and copy the "raw" link.  This works as thats what i used to test it.

![image](https://github.com/MechanicalDragon0687/BaxTools/assets/43786828/91c840de-b3b5-442c-aadd-978c3265cee2)
